NEAR = "near"
FAR = "far"
POSENC_SCALE = "posenc_scale"

FG_MASK = "fg_mask"

GLOBAL_LATENT = "global_latent"
IMAGE_FEATURES = "image_features"
FEATURE_SCALING = "feature_scaling"
NEIGHBOR_INDICES = "neighbor_indices"
NEIGHBOR_IMAGES = "neighbor_images"
NEIGHBOR_CAMERAS = "neighbor_cameras"
DEFAULT_SCENE_METADATA = "default_scene_metadata"

RGB = "rgb"
FEATURES = "features"
DEPTH = "depth"
ACCUMULATION = "accumulation"
ACCUMULATION_FEATURES = "accumulation_features"
ALIGNMENT_LOSS = "alignment_loss"
VALID_ALIGNMENT = "valid_alignment"
NEIGHBOR_RESULTS = "neighbor_results"
NEIGHBOR_PTS3D = "neighbor_pts3d"
NEIGHBOR_DEPTH = "neighbor_depth"